import os
import re

def remove_emojis(text):
    # Very basic emoji removal (removing non-ascii characters that are likely emojis)
    # We'll just strip out common emoji ranges or use a library if available.
    # Instead, let's just strip actual emoji characters using a regex pattern.
    emoji_pattern = re.compile(
        u"(\ud83d[\ude00-\ude4f])|"  # emoticons
        u"(\ud83c[\udf00-\uffff])|"  # symbols & pictographs (1 of 2)
        u"(\ud83d[\u0000-\uddff])|"  # symbols & pictographs (2 of 2)
        u"(\ud83d[\ude80-\udeff])|"  # transport & map symbols
        u"(\ud83c[\udde0-\uddff])"  # flags (iOS)
        "+", flags=re.UNICODE)
    # Actually, a simpler way in python 3 is to encode to ascii and ignore, but that strips all unicode.
    # Let's just remove the ones we know are there: , , , , , , , , , , , , , , , , , , 
    known_emojis = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
    for e in known_emojis:
        text = text.replace(e, "")
    return text

def remove_em_dashes(text):
    return text.replace(":", ":").replace(":", ":")

tooltip_dict = {
    "CAC": "Customer Acquisition Cost: The total cost to acquire a new customer.",
    "Churn": "The percentage of customers or revenue lost during a given period.",
    "AOV": "Average Order Value: The average amount spent each time a customer places an order.",
    "Margin": "Gross Margin: The percentage of total sales revenue that the company retains after incurring the direct costs.",
    "LTV": "Lifetime Value: The total expected revenue or profit from a customer over their relationship with the company.",
    "COGS": "Cost of Goods Sold: The direct costs attributable to the production of the goods sold in a company.",
    "Volume": "The total number of transactions or items sold.",
    "Split": "The percentage division of fees between different parties (e.g., buyer and seller).",
    "Discount": "The reduction in the original price of a product or service.",
    "Refund": "The percentage or amount of purchases returned by customers.",
    "Rate": "A measure, quantity, or frequency, typically one measured against some other quantity or measure.",
    "Take": "Take Rate: The fee a marketplace charges on a transaction.",
    "Elasticity": "A measure of a variable's sensitivity to a change in another variable, usually price.",
    "Sessions": "A group of user interactions with your website that take place within a given time frame.",
    "Dropoff": "The rate at which users leave the funnel at a specific step.",
    "Mobile": "Interactions occurring on mobile devices.",
    "Spend": "The amount of money allocated or used for advertising or marketing.",
    "Revenue": "The total amount of income generated by the sale of goods or services related to the company's primary operations.",
    "Sellers": "The number of active sellers on the marketplace.",
    "Buyers": "The number of active buyers on the marketplace.",
}

def get_help_text(label):
    desc = "Adjust this parameter to see its impact on the model."
    for key, val in tooltip_dict.items():
        if key.lower() in label.lower():
            desc = val
            break
    return f'help="{desc}"'

def process_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()

    # Clean emojis and em-dashes
    content = remove_emojis(content)
    content = remove_em_dashes(content)

    # Regex to find st.slider, st.number_input, st.selectbox, st.metric
    # We want to add `help="..."` to them if it doesn't exist.
    # Note: Regex parsing python code is fragile, but we'll do a simple string replacement for known patterns.
    # We'll match: st.slider("LABEL", ..., help="Adjust this parameter to see its impact on the model.") -> st.slider("LABEL", ..., help="...")
    
    # Let's use re.sub with a function
    def replacer(match):
        func = match.group(1)
        label_quote = match.group(2)
        label_text = match.group(3)
        rest = match.group(4)
        
        # If it already has help=, skip
        if "help=" in rest:
            return match.group(0)
            
        help_str = get_help_text(label_text)
        
        # We need to insert help_str at the end of the arguments, before the closing paren.
        # This is tricky because the closing paren might be on another line or part of a nested call.
        # But for simple calls on one line:
        if ")" in rest:
            # find the last parenthesis and insert before it
            last_paren_idx = rest.rfind(")")
            new_rest = rest[:last_paren_idx] + f", {help_str}" + rest[last_paren_idx:]
            return f'st.{func}({label_quote}{label_text}{label_quote}{new_rest}'
        
        return match.group(0)

    # Pattern: st.(slider|number_input|selectbox|metric)( ["']([^"']+)["'] (.*?) )
    # This is a very simplified pattern and assumes the label is the first argument and a simple string literal.
    pattern = r'st\.(slider|number_input|selectbox|metric)\(\s*(["\'])(.*?)\2(.*?\))'
    content = re.sub(pattern, replacer, content, flags=re.DOTALL)
    
    # Add expander to pages/*.py if not already there
    if "pages/" in filepath and "Concept Playbook" not in content and "def " not in content[:50]:
        # find the first st.markdown or title and insert after it
        lines = content.split('\n')
        insert_idx = -1
        for i, line in enumerate(lines):
            if "st.markdown" in line and "header" in line.lower():
                insert_idx = i + 2
                break
        
        if insert_idx != -1:
            expander_code = """
with st.expander("Concept Playbook: How to use this page"):
    st.markdown('''
    **Overview:** This page provides causal insights into your metrics.
    **How to use:** Adjust the inputs in the sidebar or main area to simulate different business scenarios. 
    Pay attention to the outputs with tooltips for detailed definitions. All metrics are connected to the central causal model.
    ''')
"""
            lines.insert(insert_idx, expander_code)
            content = '\n'.join(lines)

    with open(filepath, 'w') as f:
        f.write(content)

# Process all files
for root, dirs, files in os.walk('.'):
    if 'venv' in root or '.git' in root or '__pycache__' in root:
        continue
    for file in files:
        if file.endswith('.py'):
            filepath = os.path.join(root, file)
            try:
                process_file(filepath)
            except Exception as e:
                print(f"Error processing {filepath}: {e}")

print("Done processing files.")
